name: Eldorado Price Tracker

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installa librerie
        run: |
          pip install gspread oauth2client playwright
          playwright install chromium

      - name: Avvia tracker
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python tracker.py
